apiVersion: 1

datasources:
  - name: Host SQLite
    uid: host-sqlite
    type: frser-sqlite-datasource
    access: proxy
    editable: true
    isDefault: false
    jsonData:
      path: /var/lib/grafana/host-data/host_metrics.db
  - name: Docker PostgreSQL
    uid: docker-postgres
    type: postgres
    access: proxy
    editable: true
    isDefault: true
    url: postgres-db:5432
    user: grafana
    jsonData:
      database: metrics
      sslmode: disable
    secureJsonData:
      password: grafana
  - name: Docker MySQL
    uid: docker-mysql
    type: mysql
    access: proxy
    editable: true
    isDefault: false
    url: mysql-db:3306
    user: grafana
    jsonData:
      database: analytics
      tlsSkipVerify: true
    secureJsonData:
      password: grafana
